title: MIT 6.828 2019 学习笔记
email: guchounongyin@gmail.com
baseurl: "/mit-6.828-2019fall-notes"
url: "https://gcnyin.github.io"
github_username: gcnyin

theme: minima

disqus:
  shortname: gcnyin
minima:
  date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed