site_name: Mit 6.828 Notes
site_description: "记录学习6.828的过程、心得和踩过的坑"
site_url: "https://gcnyin.github.io/mit-6.828-2019fall-notes/"
repo_name: gcnyin/mit-6.828-2019fall-notes
repo_url: https://github.com/gcnyin/mit-6.828-2019fall-notes
site_author: gcnyin
copyright: "Copyright &copy; 2020 gcnyin"
nav:
  - 主页: index.md
  - 一些建议: suggestions.md
  - 踩坑指南: faq.md
  - 关于: about.md
  - Chapter1:
      - System Call: chapter1/system-call.md
      - File Descriptor: chapter1/file-descriptor.md
      - Pip Implementation: chapter1/riscv-pipe-implementation.md
  - Lab1:
      - Golang版Primes: lab1/csp.md
      - ls实现注释: lab1/ls.md
theme:
  language: "zh"
  palette:
    primary: "Light Green"
    accent: "Light Green"
  feature:
    tabs: true
  name: material
  font: false

extra:
  disqus: "gcnyin"
  social:
    - type: "github"
      link: "https://github.com/gcnyin"

markdown_extensions:
  - codehilite
